import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import SearchIcon from "@mui/icons-material/Search";
import VisibilityIcon from "@mui/icons-material/Visibility";
import { createStitchingOrder, getAllStitchingOrders, getStitchingOrderDetails, updateStitchingOrderStage } from "../../services/stitchingOrderApi";

const stages = ["Cutting", "Stiching", "Kaje-Button", "Press", "Ready"];
const styleForStage = { Cutting: ["#c2410c", "#ffedd5"], Stiching: ["#5b21b6", "#ede9fe"], "Kaje-Button": ["#0f766e", "#ccfbf1"], Press: ["#be185d", "#fce7f3"], Ready: ["#15803d", "#dcfce7"] };
const listFrom = (response) => Array.isArray(response) ? response : response?.data ?? response?.content ?? response?.orders ?? [];
const valueFrom = (source, keys, fallback = "") => keys.map((key) => source?.[key]).find((value) => value !== undefined && value !== null && value !== "") ?? fallback;
const dateOnly = (value) => String(value || "").slice(0, 10);
const normalize = (order, index) => {
  const id = String(order.stOrderId ?? order.id ?? order.orderId ?? `ST-${String(index + 1).padStart(3, "0")}`);
  const customer = typeof order.customer === "object" ? order.customer?.name : order.customer;
  const stage = order.currentStage ?? order.stage ?? order.status ?? "Cutting";
  return { ...order, id, stOrderId: id, srNo: order.srNo ?? order.serialNo ?? index + 1, billNo: order.billNo ?? order.billNumber ?? order.billnumber ?? "-", orderDate: dateOnly(order.orderDate), customerId: order.customerId ?? "-", customerName: customer ?? order.customerName ?? "-", garmentType: order.garmentType ?? order.garment ?? "-", quantity: order.quantity ?? 0, currentStage: stage, deliveryDate: dateOnly(order.deliveryDate ?? order.delivery), notes: order.notes ?? order.productionNoted ?? order.productionNotes ?? order.productionNote ?? order.note ?? "" };
};
const Stage = ({ value, onContextMenu }) => { const [color, background] = styleForStage[value] ?? ["#475569", "#f1f5f9"]; return <Chip label={value} size="small" onContextMenu={onContextMenu} sx={{ color, backgroundColor: background, fontWeight: 700, cursor: "context-menu" }} />; };

const Inventory = () => {
  const [tab, setTab] = useState(0), [orders, setOrders] = useState([]), [selected, setSelected] = useState(null), [query, setQuery] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(true), [billNo, setBillNo] = useState(""), [bill, setBill] = useState(null), [notes, setNotes] = useState(""), [fetching, setFetching] = useState(false), [saving, setSaving] = useState(false), [stageOrder, setStageOrder] = useState(null), [stage, setStage] = useState(""), [stageSaving, setStageSaving] = useState(false);
  const loadOrders = async () => { setLoading(true); try { const next = listFrom(await getAllStitchingOrders()).map(normalize); setOrders(next); setSelected((current) => next.find((item) => item.id === current?.id) ?? next[0] ?? null); setError(""); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { loadOrders(); }, []);
  const filtered = useMemo(() => orders.filter((order) => Object.values(order).join(" ").toLowerCase().includes(query.toLowerCase())), [orders, query]);
  const fetchBill = async () => { if (!billNo.trim()) return setError("Enter a bill number first."); setFetching(true); setError(""); try { const response = await getStitchingOrderDetails(billNo.trim()); const data = response?.data ?? response?.bill ?? response; setBill(data); setNotes(valueFrom(data, ["productionNoted", "productionNotes", "productionNote", "notes", "note"])); } catch (err) { setBill(null); setError(err.message); } finally { setFetching(false); } };
  const createOrder = async (event) => { event.preventDefault(); if (!bill) return setError("Fetch a bill before creating the order."); const form = new FormData(event.currentTarget); const deliveryDate = dateOnly(valueFrom(bill, ["deliveryDate", "dueDate", "expectedDelivery"])); setSaving(true); try { await createStitchingOrder({ billNo: valueFrom(bill, ["billNo", "billNumber"], billNo), orderDate: dateOnly(valueFrom(bill, ["billCreatedDate", "billDate", "createdDate", "orderDate"])), customerId: valueFrom(bill, ["customerId", "custId", "customer"]), customerName: valueFrom(bill, ["customerName", "custName", "name"]), garmentType: form.get("garment"), expectedDelivery: deliveryDate, deliveryDate, quantity: form.get("quantity"), notes }); await loadOrders(); setTab(1); setBill(null); setNotes(""); event.currentTarget.reset(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const saveStage = async () => { setStageSaving(true); try { await updateStitchingOrderStage(stageOrder.billNo, stage); const updated = { ...stageOrder, currentStage: stage }; setOrders((current) => current.map((item) => item.id === stageOrder.id ? updated : item)); setSelected((current) => current?.id === stageOrder.id ? updated : current); setStageOrder(null); } catch (err) { setError(err.message); } finally { setStageSaving(false); } };
  const detail = selected && <Paper sx={{ p: 2, mt: 2, border: "1px solid #e3eaf3" }}><Typography sx={{ fontWeight: 800, mb: 1 }}>Order #{selected.stOrderId}</Typography><Box sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1 }}>{[["SR.NO", selected.srNo], ["ST_ORDERID", selected.stOrderId], ["BILLNO", selected.billNo], ["ORDER DATE", selected.orderDate], ["CUSTOMERID", selected.customerId], ["CUSTOMER NAME", selected.customerName], ["GARMENT TYPE", selected.garmentType], ["QUANTITY", selected.quantity], ["CURRENT STAGE", selected.currentStage], ["DELIVERY DATE", selected.deliveryDate]].map(([label, value]) => <Box key={label}><Typography sx={{ fontSize: 10, color: "#94a3b8", fontWeight: 700 }}>{label}</Typography><Typography sx={{ fontSize: 12 }}>{value}</Typography></Box>)}</Box><Box sx={{ mt: 2, p: 1.3, background: "#f6f9fc" }}><Typography sx={{ fontSize: 11, fontWeight: 800 }}>PRODUCTION NOTES</Typography><Typography sx={{ fontSize: 11, whiteSpace: "pre-wrap", color: selected.notes ? "#475569" : "#94a3b8" }}>{selected.notes || "No production notes added."}</Typography></Box></Paper>;
  return <Box sx={{ minHeight: "calc(100vh - 40px)", display: "flex", flexDirection: "column", color: "#183153" }}>{error && <Alert severity="error" sx={{ mb: 2 }} action={<Button onClick={loadOrders}>Retry</Button>}>{error}</Alert>}<Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", md: "center" }} spacing={2} sx={{ mb: 2.5 }}><Stack direction="row" spacing={1.1} alignItems="baseline"><Typography variant="h4" sx={{ fontWeight: 800, letterSpacing: 0, fontSize: { xs: 28, md: 30 } }}>Stitching / Production Tracking</Typography><Typography sx={{ color: "#64748b", fontSize: 12 }}>Track every garment from order received to delivery.</Typography></Stack><Button variant="contained" startIcon={<AddIcon />} onClick={() => setTab(0)} sx={{ textTransform: "none", fontWeight: 600, borderRadius: 2, px: 2 }}>New Stitching Order</Button></Stack><Box sx={{ borderBottom: "2px solid #e7edf5", mb: 2.5 }}><Tabs value={tab} onChange={(_, value) => setTab(value)} sx={{ "& .MuiTab-root": { textTransform: "none", fontWeight: 600, fontSize: 15, color: "#64748b", "&.Mui-selected": { color: "#1266d8" } }, "& .MuiTabs-indicator": { backgroundColor: "#1266d8" } }}><Tab label="Create Stitching Order" /><Tab label="View All Orders" /><Tab label="View By Order ID" /></Tabs></Box>
    {tab === 0 && <Paper component="form" onSubmit={createOrder} sx={{ p: { xs: 2, md: 3 }, maxWidth: 900, border: "1px solid #e3eaf3", boxShadow: "0 2px 8px rgba(41, 72, 112, .04)" }}><Typography sx={{ fontWeight: 800, fontSize: 18, mb: .5 }}>Create Stitching Order</Typography><Typography sx={{ color: "#64748b", fontSize: 12, mb: 2.5 }}>Fetch a bill first, then add the garment details for production.</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ mb: 2.5 }}><TextField label="Enter Bill Number" type="number" value={billNo} onChange={(event) => { setBillNo(event.target.value); setBill(null); }} required fullWidth size="small" /><Button type="button" variant="contained" onClick={fetchBill} disabled={fetching} sx={{ textTransform: "none", fontWeight: 600, minWidth: 120 }}>{fetching ? "Fetching..." : "Fetch Bill"}</Button></Stack>{bill && <Alert severity="success" sx={{ mb: 2 }}>Bill loaded successfully.</Alert>}<Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr" }, gap: 2 }}><TextField label="Customer ID" value={valueFrom(bill, ["customerId", "custId", "customer"])} disabled size="small" /><TextField label="Customer Name" value={valueFrom(bill, ["customerName", "custName", "name"])} disabled size="small" /><TextField name="garment" label="Garment Type" select defaultValue="Shirt (Full Sleeve)" disabled={!bill} size="small">{["Shirt (Full Sleeve)", "Shirt (Half Sleeve)", "Pant (Formal)", "Blazer", "Kurta", "Jacket"].map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField><TextField name="delivery" label="Delivery Date" type="date" value={dateOnly(valueFrom(bill, ["deliveryDate", "dueDate", "expectedDelivery"]))} disabled InputLabelProps={{ shrink: true }} size="small" /><TextField name="quantity" label="Quantity" type="number" defaultValue="1" disabled={!bill} size="small" /><TextField label="Production Notes" multiline minRows={3} value={notes} onChange={(event) => setNotes(event.target.value)} disabled={!bill} size="small" sx={{ gridColumn: { sm: "1 / -1" } }} /></Box><Button type="submit" variant="contained" disabled={!bill || saving} sx={{ mt: 2, textTransform: "none", fontWeight: 600 }}>{saving ? "Creating..." : "Create Order"}</Button></Paper>}
    {tab === 1 && <Box><TextField value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search all order columns" size="small" fullWidth sx={{ mb: 2 }} InputProps={{ startAdornment: <SearchIcon sx={{ mr: 1 }} /> }} />{loading ? <Typography>Loading stitching orders...</Typography> : <Paper sx={{ overflowX: "auto" }}><Box sx={{ minWidth: 1450 }}><Box sx={{ display: "grid", gridTemplateColumns: "70px 115px 85px 110px 105px 155px 145px 80px 125px 115px 1fr", gap: 1, p: 1.5, background: "#f7faff", fontSize: 10, fontWeight: 800 }}>{["SR.NO", "ST_ORDERID", "BILLNO", "ORDER DATE", "CUSTOMERID", "CUSTOMER NAME", "GARMENT TYPE", "QUANTITY", "CURRENT STAGE", "DELIVERY DATE", "PRODUCTION NOTES"].map((label) => <span key={label}>{label}</span>)}</Box>{filtered.map((order) => <Box key={order.id} onClick={() => setSelected(order)} sx={{ display: "grid", gridTemplateColumns: "70px 115px 85px 110px 105px 155px 145px 80px 125px 115px 1fr", gap: 1, alignItems: "center", p: 1.5, borderTop: "1px solid #eef2f7" }}><span>{order.srNo}</span><span>{order.stOrderId}</span><span>{order.billNo}</span><span>{order.orderDate}</span><span>{order.customerId}</span><span>{order.customerName}</span><span>{order.garmentType}</span><span>{order.quantity}</span><Box onContextMenu={(event) => { event.preventDefault(); setStageOrder(order); setStage(order.currentStage); }}><Stage value={order.currentStage} /></Box><span>{order.deliveryDate}</span><span>{order.notes || "-"}</span></Box>)}</Box></Paper>}{detail}</Box>}
    {tab === 2 && <Paper sx={{ p: 3, maxWidth: 900 }}><Stack direction="row" spacing={1}><TextField value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Enter ST_ORDERID" fullWidth /><Button variant="contained" startIcon={<VisibilityIcon />} onClick={() => setSelected(orders.find((item) => item.stOrderId.toLowerCase() === query.trim().toLowerCase()) || null)}>View</Button></Stack>{detail}</Paper>}
    <Dialog open={Boolean(stageOrder)} onClose={() => !stageSaving && setStageOrder(null)} fullWidth maxWidth="xs"><DialogTitle>Change Current Stage</DialogTitle><DialogContent><Typography sx={{ mb: 2 }}>Order: {stageOrder?.stOrderId}</Typography><TextField select fullWidth label="Stage" value={stage} onChange={(event) => setStage(event.target.value)}>{stages.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField></DialogContent><DialogActions><Button onClick={() => setStageOrder(null)}>Cancel</Button><Button variant="contained" onClick={saveStage} disabled={stageSaving}>{stageSaving ? "Updating..." : "Update Stage"}</Button></DialogActions></Dialog>
  </Box>;
};
export default Inventory;
